\hypertarget{classpip_1_1__internal_1_1exceptions_1_1CommandError}{}\doxysection{pip.\+\_\+internal.\+exceptions.\+Command\+Error Class Reference}
\label{classpip_1_1__internal_1_1exceptions_1_1CommandError}\index{pip.\_internal.exceptions.CommandError@{pip.\_internal.exceptions.CommandError}}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raised when there is an error in command-line arguments\end{DoxyVerb}
 Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Command\+Error\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=3.000000cm]{classpip_1_1__internal_1_1exceptions_1_1CommandError}
\end{center}
\end{figure}


The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/\+Lib/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
