\hypertarget{classpip_1_1__vendor_1_1requests_1_1exceptions_1_1ConnectTimeout}{}\doxysection{pip.\+\_\+vendor.\+requests.\+exceptions.\+Connect\+Timeout Class Reference}
\label{classpip_1_1__vendor_1_1requests_1_1exceptions_1_1ConnectTimeout}\index{pip.\_vendor.requests.exceptions.ConnectTimeout@{pip.\_vendor.requests.exceptions.ConnectTimeout}}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}The request timed out while trying to connect to the remote server.

Requests that produced this error are safe to retry.
\end{DoxyVerb}
 Inheritance diagram for pip.\+\_\+vendor.\+requests.\+exceptions.\+Connect\+Timeout\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=3.660131cm]{classpip_1_1__vendor_1_1requests_1_1exceptions_1_1ConnectTimeout}
\end{center}
\end{figure}
\doxysubsection*{Additional Inherited Members}


The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/\+Lib/site-\/packages/pip/\+\_\+vendor/requests/exceptions.\+py\end{DoxyCompactItemize}
